#ifndef ALL_FUNCTION_HEADERS_H
#define ALL_FUNCTION_HEADERS_H

#include "bioweapon.c"
#include "cart_add.c"
#include "cart_pay.c"
#include "cart_remove.c"
#include "cart_show.c"
#include "console.c"
#include "help.c"
#include "history.c"
#include "load.c"
#include "login.c"
#include "logout.c"
#include "main.c"
#include "profile.c"
#include "quit.c"
#include "random_number_generator.c"
#include "register.c"
#include "save.c"
#include "start.c"
#include "store_list.c"
#include "store_remove.c"
#include "store_request.c"
#include "store_supply.c"
#include "wishlist_add.c"
#include "wishlist_clear.c"
#include "wishlist_remove.c"
#include "wishlist_show.c"
#include "wishlist_swap.c"
#include "work_challenge.c"

#endif
