#ifndef ALL_FUNCTION_HEADERS_H
#define ALL_FUNCTION_HEADERS_H

#include "load.h"
#include "bioweapon.h"
#include "save.h"
#include "cart_add.h"
#include "cart_pay.h"
#include "cart_remove.h"
#include "cart_show.h"
#include "help.h"
#include "history_show.h"
#include "login.h"
#include "logout.h"
#include "profile.h"
#include "quit.h"
#include "random_number_generator.h"
#include "register.h"
#include "store_list.h"
#include "store_remove.h"
#include "store_request.h"
#include "store_supply.h"
#include "wishlist_add.h"
#include "wishlist_clear.h"
#include "wishlist_remove.h"
#include "wishlist_show.h"
#include "wishlist_swap.h"
#include "work.h"
#include "start.h"
#include "work_challenge.h"

#endif